### ISSUE TITLE
python3 Jarvis.py

### ISSUE THREAD

**Issue by tomasalias** [KushalLimbasiya/Base-of-Self-Aware-AI#1]
Traceback (most recent call last):
  File "/home/tomasalias/Base-of-Self-Aware-AI/Jarvis.py", line 12, in <module>
    data = torch.load(FILE)
  File "/home/tomasalias/.local/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/tomasalias/.local/lib/python3.10/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/tomasalias/.local/lib/python3.10/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'TrainData.pth'

**Comment by AiWhispererMax** [comment]
I have self-aware AI now, if you care. Would like to meet others who do.
